language: python
python:
  - "3.6"
cache:
 directories:
   # - $HOME/.cache/pip
   # - $HOME/.npm
   # - node_modules

before_install:
- set -e
- . $HOME/.nvm/nvm.sh
- nvm install 10.15.3
- nvm use 10.15.3
- rm -rf node_modules
- npm install
- npm install web3@1.0.0-beta.37 ethereumjs-util ethereumjs-abi --no-save
- git checkout package.json package-lock.json
- sudo apt-get install python3-pip
- python3 --version
- python2 --version
- pip3 --version
- sudo -H pip install --upgrade setuptools
- sudo -H pip install --upgrade pip wheel requests pyopenssl
- sudo -H pip install --ignore-installed six
- sudo -H pip install --upgrade tox twine
- pip install --upgrade setuptools
- pip install --upgrade web3 aiohttp requests cryptography pyopenssl
- pip2 install requests[security]
- git pull --tags
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "teatien-master" ]; then npm config set git-tag-version=false && NPM_VERSION=$(npm version patch); fi
- npm run build
- cd python
- tox -e doc
- cd ..
# - npm run test-base
# - bash -c 'node run-tests --js --python 5' 2>&1
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "teatien-master" ]; then env COMMIT_MESSAGE=${NPM_VERSION:1} GITHUB_TOKEN=${GITHUB_TOKEN} ./build/push.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "teatien-master" ]; then cd python && env PYPI_PASSWORD=${PYPI_PASSWORD} ./deploy.sh && cd ..; fi
after_failure:
- dmesg | grep -i kill
deploy:
  - provider: npm
    email: thrall.chen@gmail.com
    api_key: ${NPM_TOKEN}
      
env:
  global:
    secure: CQBKPcipKTvfgBi8KXaJ6KyjJL5GcWPEW7WrKZcTeM2AaNqTX8w3yuqjsezxVnQWLG3TzEI0m1K31Fv9wfZHsMwRIr5py6AeAc4C2JgaKs3FSAFJ3m46a9hK7FIeC0xMdXszPJx7534XiuG8nMJRbwbNNswb35GekysKU87g5Sf6U7UFFeyyyQdchiPF85lYBt/AJSArNsfHMd0RKQY5pHdAHNNB70qFECIBeC6MYiUFBHydw2ist/bSWa9GYEh3LxUNMQ7bbxuzD6+sVMU2PW61gEpa3I9HB7NTQvPp+YbYWqBwS++SKCuqkalXdMPeCIINu64T1UtFGZNWvw9xfg8T8GwGHwZnNZ1o3WCXKo9/+FC70OAb76mblEXllhQs+gBL5g/bqdQBKfGrYIACHBRE3pzNPSRn7oY3hpk7NLoJRbB28OQ5ymJrDc8hctoXwgD3KrIM91+6YqycOifidLFHecg/VA2bjSx/ql69sVhNchaBJ8b7EMMIjo1DrFIv43XJ7DHX+2yZFJD8uv5eCGHkfXv6XfV5312TYzGYsxpfJ9my9tdTGxop2BXzaf1nYqrI+RPKIZrh6FgiXgRaetwRpWl4G+DqxKbKtfzYlZtYU2JeJ7Z5AMwLHyvxxcuOH3MrE+vk5nbU5gE9E3m5o7yH+d7Qj5liCyXk0zxijn0=
